### ISSUE TITLE
Can't update panel if it's currently in use

### ISSUE THREAD

**Issue by TheQwertiest** [TheQwertiest/foo_spider_monkey_panel#137]
See https://github.com/TheQwertiest/foo_spider_monkey_panel/issues/134#issuecomment-840517118 for a problem that can occur because of this bug.

**Comment by TheQwertiest** [comment]
Note to self: try to make update operation atomic, i.e. store the old package somewhere before replacing\removing it's files and restore it if update fails.

**Comment by Wil-B** [comment]
I tested v1.4.2-dev+bae2dd0e. 

It seems better, but unfortunately not without issues for me that can result in lost settings and the panel reset. I tested on a portable install.

It seems OK provided the packages folder isn't open in windows explorer. That's when I've seen the issues.

With the packages folder open in windows explorer the following happened:

1) Choose package manager. Click import.

2) Asks 'Do you want to update? Click yes.

The package is currently in use. Changes will be applied on the next foobar2000 start.
Do you want to restart now?

Click: Yes

The follow messages were obtained:

```
Failed to process delayed packages: create_directories: Access is denied.: "Z:\fb2kprofile\profile\foo_spider_monkey_panel\packages\{F5E9D9EB-42AD-4A47-B8EE-C9877A8E7851}"
```

```
Can't find the required package: `{F5E9D9EB-42AD-4A47-B8EE-C9877A8E7851} (Find & Play by WilB)`
```
```
Can't load panel settings. Your panel will be completely reset!
```

So, panel was wiped and all settings in panel properties lost!

I guess normal users wouldn't have the packages folder open; it was just me testing. But it would be better to handle this scenario if possible.

**Comment by TheQwertiest** [comment]
Not sure if I can do anything about it: at some point files need to be deleted for the package to be updated.
I'll try to find a way a way to check if a file is in use, but I'm afraid that such checks will be really slow.

**Comment by Wil-B** [comment]
Updating a package
- as noted above, a packages folder open in windows explorer seems to cause updating to fail
- a file set to read-only seems to cause update to fail. In my case one of the images files had read-only set and it seems that was what was causing the issue referred to above with standard install.

Unfortunately, there is no warning with either of these so user can't abort. Result may be package is corrupted, panel settings lost or panel reset. If update fails for any reason, then I thought the idea was to restore the old package & settings?

**Comment by TheQwertiest** [comment]
@Wil-B added more fallbacks during package update

**Comment by Wil-B** [comment]
It worked gracefully for the read-only scenario.

But clicking packages folder in windows explorer, then trying to update, still resulted in a panel reset & loss of settings in panel properties.

May be if its not fixable, there should be a warning message somewhere something like: Ensure windows explorer is closed before proceeding.

**Comment by TheQwertiest** [comment]
that's really weird, my workaround shoould've worked for both cases

**Comment by TheQwertiest** [comment]
the problem is that I can't even reproduce "locked folder" scenario (OS differences?)

**Comment by TheQwertiest** [comment]
Do you still recieve exactly the same error message? I.e. `Failed to process delayed packages: create_directories: Access is denied.: "Z:\fb2kprofile\profile\foo_spider_monkey_panel\packages\{F5E9D9EB-42AD-4A47-B8EE-C9877A8E7851}"`

Do you have any files in said folder after update fails?

**Comment by Wil-B** [comment]
windows 10.  I have this folder open:

```
Z:\fb2kprofile\profile\foo_spider_monkey_panel\packages
```
Packages folder is **expanded**

On trying to update:

Three error messages:
```
Failed to process delayed packages: recursive_directory_iterator::recursive_directory_iterator: The system cannot find the path specified.: "Z:\fb2kprofile\profile\foo_spider_monkey_panel\packages\{E85C9EF0-778B-46DD-AF20-F4BE831360DD}"
Can't find the required package: `{E85C9EF0-778B-46DD-AF20-F4BE831360DD} (Library Tree by Wilb)
Can't load panel settings. Your panel will be completely reset!
```
The folder in question: {E85C9EF0-778B-46DD-AF20-F4BE831360DD} is removed from packages

The new one is in tmp\\packages_to_install\\{E85C9EF0-778B-46DD-AF20-F4BE831360DD}
tmp also ends up having an empy folder: unpacked_packages (may be after restart)

Restarting foobar2000 the gives the following on each restart;
```
Failed to process delayed packages: copy: The system cannot find the file specified.: "Z:\fb2kprofile\profile\foo_spider_monkey_panel\packages\{E85C9EF0-778B-46DD-AF20-F4BE831360DD}", "Z:\fb2kprofile\profile\foo_spider_monkey_panel\tmp\unpacked_package"
```

**Comment by TheQwertiest** [comment]
I still can't reproduce your error, but I've added another safeguard, that will hopefully fix your issue.

**Comment by Wil-B** [comment]
Mostly it was OK, but not always.

Panel ended up reset in ~ 2 out of 10 tries.

**Comment by TheQwertiest** [comment]
Added another safe-guard, can you try again, plz?
Oh and if it fails again, could you attach the error message and describe package folder contents?

**Comment by Wil-B** [comment]
Sorry no luck
1st try: panel reset during update & usual 3 errors
2nd try: restored old package, but panel then reset on restarting foobar2000

packages folder contains 3 packages
bio
library tree
find & play
these are available in uploads

test is with library tree, set to show album art (context menu)

Unrelated:
a) unresponsive script warning now seems to comes on if right click context menu open for a few seconds (I pretty sure it didn't before)
b) There was also this folder lock [issue](https://hydrogenaud.io/index.php?topic=112914.msg998358#msg998358) with images.
I haven't put it as a new issue in case your not interested in fixing or can't fix. It's weird; image is released but not the folder in scenarios in post.

**Comment by TheQwertiest** [comment]
I really don't like this behaviour...
BTW, do you happen to use AV software? And what is your fs format (i.e. fat32, ntfs or smth else)?

> a) unresponsive script warning now seems to comes on if right click context menu open for a few seconds (I pretty sure it didn't before)

Does it happen on the Attempt III build?

> b) There was also this folder lock issue with images.

I've encountered this as well, but I don't think I can fix this without replacing whole image loading stack (which I'm planning to). Relevant WinAPI docs say that it should not happen, but, as we can see, it does...

**Comment by TheQwertiest** [comment]
Can you try renaming package folder from command line while you are "locking" the parent folder and see if it works?
E.g. `ren {E85C9EF0-778B-46DD-AF20-F4BE831360DD} {E85C9EF0-778B-46DD-AF20-F4BE831360DD}_tmp`

**Comment by TheQwertiest** [comment]
Also, are you sure that error are the same? I.e. `rerecursive_directory_iterator` error

**Comment by Wil-B** [comment]
v1.4.2-dev+6c0a591c: attempt III

Package loading issue occur with that version.

ntfs; standard windows virus protection (windows defender)

Yes error when updating was:

Failed to process delayed packages: exists: Access is denied.: "Z:\fb2kprofile\profile\foo_spider_monkey_panel\packages\{E85C9EF0-778B-46DD-AF20-F4BE831360DD}"

ren -  I didn't seem to get syntax right

Unresponsive script on menu seems fixed in v1.4.2-dev+305e7594

**Comment by Wil-B** [comment]
Actually v1.4.2-dev+305e7594 is behaving much better v1.4.2-dev+6c0a591c. I haven't had any panel reset while packages folder open & expanded in windows explorer in 20 tries. Seems rather odd since I didn't think relevant changes were made (makes me wonder if updated changes were actually in v1.4.2-dev+6c0a591c).

But if the actual image folder (noCover) is open its prone to corrupting the package as some, but not all,  files are removed and so gave script error due to missing file. At least panel properties were retained...

```
Error: Spider Monkey Panel v1.4.2-dev+305e7594 ({62766B07-DABB-45C9-8B6A-7F3B42E53DC9}: Library Tree v2.2.0-Beta.2 by Wilb)
include failed:
ReadTextFile failed:
Path does not point to a valid file: Z:\fb2kprofile\profile\foo_spider_monkey_panel\packages\{E85C9EF0-778B-46DD-AF20-F4BE831360DD}\assets\html\config.html

File: utils.js
Line: 6, Column: 40
Stack trace:
  @y_utils.getAsset@267a4245fe5483a2dca54fb6f3cfd762:6:40
  @etHtmlCode@6a47f42b2d91a0fe064c3706b1f4f057:28:34
  @opUpBox@6a47f42b2d91a0fe064c3706b1f4f057:3:8
  @initialise.js:10:18
  @eadFiles@027f9a902e89a1e2be5152a2f20f39b7:10:10
  @sync*@027f9a902e89a1e2be5152a2f20f39b7:34:1

```

**Comment by TheQwertiest** [comment]
I'm revamping this again, which will hopefully result in a better experience.

**Comment by TheQwertiest** [comment]
Revamped, try this one, plz.
It should be more robust and has a recovery helper in case it still fails.

**Comment by TheQwertiest** [comment]
Fixed small bugs

**Comment by Wil-B** [comment]
It seems much better .

I tried it ~40 times. In that time I didn't have any panel resets.

One time with images\noCover open the package was corrupted with some files removed. But I only saw it once despite trying to reproduce again.

On further checking, it turns out that USB stick (z drive) that most tests done on is FAT32. That will normally fail to update packages in use, but is now failing gracefully (except for the above corruption noted). On the other hand main foobar2000 on c drive is ntfs & that seems able to update packages that are in use, even with noCover folder open.

**Comment by TheQwertiest** [comment]
> One time with images\noCover open the package was corrupted with some files removed. But I only saw it once despite trying to reproduce again.

Sigh... Still, I don't think I can improve this any further, so I guess we'll have to live with it...
